version: '3'

services:
  nginx:
    container_name: api-gateway
    #image: nginx-api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4200:4200
      - 433:433
    depends_on:
      - spring-boot-jpa-app
    links:
      - spring-boot-jpa-app
  mysql-docker-container:
    container_name: mysql-docker-container
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      # already root user by default so just set the pass to avoid bug
      #- MYSQL_PASSWORD=root
      #- MYSQL_USER=root
    ports:
      - 2012:3306 # <host-port>:<container-port> means we can access to 127.0.0.1:2012 (thats database from docker on local machin)
    volumes:
      #- /data/mysql
      # For test
      - ./seed/dev:/docker-entrypoint-initdb.d
      # For prod
      #- ./seed/prod:/docker-entrypoint-initdb.d
  spring-boot-jpa-app:
    container_name: spring-boot-jpa-app
    restart: always
    # these variables refers to the .env file
    image: ${DOCKER_REPOSITORY}:${TAG_DEV}${VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 4999:4999 # same as ports above, the api is accessible at 127.0.0.1:4999 (for postman)
    volumes:
      - /data/spring-boot-app
